// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Contracts;

/// <summary>Represents the 'Brand' reference-data contract.</summary>
[ReferenceData]
public partial class Brand : ReferenceData<Brand> { }

/// <summary>
/// Represents the 'Brand' reference-data contract collection.
/// </summary>
public partial class BrandCollection() : ReferenceDataCollection<Brand>(ReferenceDataSortOrder.Code) { }

#nullable restore