// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Contracts;

/// <summary>
/// Represents the 'Category' reference-data contract.
/// </summary>
[ReferenceData]
public partial class Category : ReferenceData<Category> { }

/// <summary>
/// Represents the 'Category' reference-data contract collection.
/// </summary>
public partial class CategoryCollection() : ReferenceDataCollection<Category>(ReferenceDataSortOrder.Code) { }

#nullable restore