// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Contracts;

/// <summary>
/// Represents the 'Movement Kind' reference-data contract.
/// </summary>
[ReferenceData]
public partial class MovementKind : ReferenceData<MovementKind> { }

/// <summary>
/// Represents the 'MovementKind' reference-data contract collection.
/// </summary>
public partial class MovementKindCollection() : ReferenceDataCollection<MovementKind>(ReferenceDataSortOrder.Code) { }

#nullable restore