// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Contracts;

/// <summary>
/// Represents the 'Movement Status' reference-data contract.
/// </summary>
[ReferenceData]
public partial class MovementStatus : ReferenceData<MovementStatus> { }

/// <summary>
/// Represents the 'MovementStatus' reference-data contract collection.
/// </summary>
public partial class MovementStatusCollection() : ReferenceDataCollection<MovementStatus>(ReferenceDataSortOrder.Code) { }

#nullable restore