// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Contracts;

/// <summary>
/// Represents the 'Sub Category' reference-data contract.
/// </summary>
[ReferenceData]
public partial class SubCategory : ReferenceData<SubCategory> 
{
    /// <summary>
    /// Gets or initializes the Category Code.
    /// </summary>
    [ReferenceData<Category>]
    public partial string CategoryCode { get; init; }
}

/// <summary>
/// Represents the 'SubCategory' reference-data contract collection.
/// </summary>
public partial class SubCategoryCollection() : ReferenceDataCollection<SubCategory>(ReferenceDataSortOrder.Code) { }

#nullable restore