<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="CoreEx.UnitTesting" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="UnitTestEx.Aspire" />
    <PackageReference Include="UnitTestEx.NUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\app-name.Aspire\app-name.Aspire.csproj" />
    <ProjectReference Include="..\..\tests\solution-name.Test.Common\solution-name.Test.Common.csproj" />
    <!--#if has-data-provider-->
    <ProjectReference Include="..\..\tools\solution-name.Database\solution-name.Database.csproj" />
    <!--#endif-->
  </ItemGroup>
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>
</Project>
