using solution-name.Infrastructure.Repositories;
// #if implement-servicebus
using CoreEx.Azure.Messaging.ServiceBus;
// #endif
using Microsoft.Extensions.Options;
using OpenTelemetry;
using OpenTelemetry.Trace;
using StackExchange.Redis;
using ZiggyCreatures.Caching.Fusion;
using ZiggyCreatures.Caching.Fusion.Backplane.StackExchangeRedis;

namespace app-name.Subscribe;

public class Program
{
    private static void Main(string[] args)
    {
        // Create the web builder.
        var builder = WebApplication.CreateBuilder(args);

        // Add CoreEx host settings.
        builder.AddHostSettings();

        // Add CoreEx services.
        builder.Services
            .AddPrecisionTimeProvider()
            .AddExecutionContext()
// #if refdata-enabled
            .AddReferenceDataOrchestrator()             // Resolves the (CodeGen-generated) IReferenceDataProvider from DI at runtime — no compile-time dependency on the generated type.
// #endif
            .AddMvcWebApi()
            .AddHttpWebApi()
            .AddHostedServiceManager();

        // Dynamically register all [ScopedService] types — subscribers (this host), application services, and infrastructure repositories (including those generated by CodeGen). The AssemblyMarker types are stable anchors that always exist.
        builder.Services.AddDynamicServicesUsing(typeof(Program).Assembly, typeof(solution-name.Application.AssemblyMarker).Assembly, typeof(solution-name.Infrastructure.AssemblyMarker).Assembly);

        // Add L1/L2 caching services.
        builder.Services.AddMemoryCache();              // Adds the in-memory cache - L1.
        builder.AddRedisDistributedCache("redis");      // Adds Redis as the distributed cache - L2.

        // Add and wire-up FusionCache including backplane.
        builder.Services.AddFusionCache()
            .WithRegisteredMemoryCache()
            .WithRegisteredDistributedCache()
            .WithBackplane(sp => new RedisBackplane(new RedisBackplaneOptions { Configuration = sp.GetRequiredService<IOptions<ConfigurationOptions>>().Value.ToString() }))
            .WithSystemTextJsonSerializer(JsonDefaults.SerializerOptions);

        // Add CoreEx caching services.
        builder.Services
            .AddFusionHybridCache()                     // Adds the CoreEx.Caching.IHybridCache for FusionCache.
            .AddDefaultCacheKeyProvider()               // Adds the default CoreEx.Caching.ICacheKeyProvider.
            .AddHybridCacheIdempotencyProvider();       // Adds the CoreEx.Caching.Idempotency.IIdempotencyProvider.

        // Add the repository and related database services.
// #if implement-sqlserver
        builder.AddSqlServerClient("SqlServer");        // Adds the SqlServerClient (using Aspire library).
        builder.Services
            .AddSqlServerDatabase()                     // Adds the SqlServerDatabase.
            .AddSqlServerUnitOfWork()                   // Adds the SqlServerUnitOfWork for the SqlServerDatabase.
            .AddEventFormatter()                        // Adds the EventFormatter to enable message formatting for publishing.
            .AddSqlServerOutboxPublisher()              // Adds the SqlServerOutboxPublisher as the IEventPublisher.
            .AddDbContext<domain-nameDbContext>()       // Adds the standard EF DbContext.
            .AddEfDb<domain-nameEfDb>();                // Adds the CoreEx extended EF service.
// #elif implement-postgres
        builder.AddAzureNpgsqlDataSource("Postgres");   // Adds the NpgsqlDataSource (using Aspire library).
        builder.Services
            .AddPostgresDatabase()                      // Adds the PostgresDatabase.
            .AddPostgresUnitOfWork()                    // Adds the PostgresUnitOfWork for the PostgresDatabase.
            .AddEventFormatter()                        // Adds the EventFormatter to enable message formatting for publishing.
            .AddPostgresOutboxPublisher()               // Adds the PostgresOutboxPublisher as the IEventPublisher.
            .AddDbContext<domain-nameDbContext>()       // Adds the standard EF DbContext.
            .AddEfDb<domain-nameEfDb>();                // Adds the CoreEx extended EF service.
// #endif

// #if implement-servicebus
        // Add the Azure Service Bus client and subscribe wiring.
        builder.AddAzureServiceBusClient("ServiceBus");         // Adds the Azure Service Bus client (using Aspire library).
        builder.Services.AddAzureServiceBusPublisher((_, c) =>  // Adds the service bus as the IEventPublisher.
        {
            c.SessionIdStrategy = ServiceBusSessionStrategy.UsePartitionKeyConvertedToAnId;  // Use a partition-id as the session-id.
        }, addAsDefaultIEventPublisher: false);                                              // Add as a named IEventPublisher, not the default (as the default is the OutboxPublisher).

        // Add event formatter and subscribed-manager.
        builder.Services
            .AddEventFormatter()                                                // Adds the EventFormatter to enable message parsing/formatting.
            .AddSubscribedManager((_, c) => c.AddSubscribersUsing<Program>());  // Add all subscribers from this assembly.

        // Build and create the Azure Service Bus receiving services.
        builder.Services.AzureServiceBusReceiving()
            .WithSessionReceiver(_ => ServiceBusSessionReceiverOptions.CreateForTopicSubscription())    // Set the topic and subscription, etc. from configuration.
            .WithSubscribedSubscriber()                 // Adds the service bus subscriber using the SubscribedManager.
            .WithHostedService()                        // Adds the service bus receiver as a hosted service.
            .Build();                                   // Builds all the services and adds to the service collection.
// #endif

        // Post-configure all health-checks; adds the standard tags.
        builder.Services.PostConfigureAllHealthChecks();

        // Add the ASP.NET Core services.
        builder.Services.AddControllers();

        // Add the OpenAPI services.
        builder.Services.AddOpenApiDocument(s =>
        {
            s.Title = builder.Environment.ApplicationName;
            s.AddCoreExConfiguration();
        });

        // Add OpenTelemetry tracing.
        builder.WithCoreExTelemetry()
// #if implement-sqlserver
            .WithCoreExSqlServerTelemetry()
// #elif implement-postgres
            .WithCoreExPostgresTelemetry()
// #endif
// #if implement-servicebus
            .WithCoreExServiceBusTelemetry()
// #endif
            .UseOtlpExporter();

        // Build the application.
        var app = builder.Build();

        // Configure the pipeline/middleware (order is important).
        app.UseCoreExExceptionHandler();
        app.UseHttpsRedirection();
        // app.UseAuthentication();   // TODO: register an authentication scheme (builder.Services.AddAuthentication(...)) then uncomment.
        app.UseAuthorization();
        app.UseExecutionContext();
        app.MapControllers();

        app.UseOpenApi();
        app.UseSwaggerUi();
        app.MapHealthChecks(/* Endpoints should be secured. */);
        app.MapHostedServices(/* Endpoints should be secured. */);

        // Run the application.
        app.Run();
    }
}
