

// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Api.Controllers;

/// <summary>Represents the <see cref="Brand"/> reference-data controller.</summary>
[ApiController, Route("/api/refdata/brands")]
public partial class BrandController(CoreEx.AspNetCore.Mvc.WebApi webApi, IReferenceDataService service) : ControllerBase
{
    private readonly CoreEx.AspNetCore.Mvc.WebApi _webApi = webApi.ThrowIfNull();
    private readonly IReferenceDataService _service = service.ThrowIfNull();

    [HttpGet("{id}"), HttpHead("{id}")]
    [ProducesResponseType(typeof(Brand), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> GetAsync(string id,CancellationToken cancellationToken)
        => _webApi.GetWithResultAsync(Request, (_, ct) => _service.GetBrandAsync(id.Required(), ct), cancellationToken: cancellationToken);

    [HttpPost]
    [Accepts<Brand>]
    [ProducesResponseType<Brand>(201)]
    [IdempotencyKey]
    public Task<IActionResult> CreateAsync(CancellationToken cancellationToken) => _webApi.PostWithResultAsync<Brand, Brand>(Request, (ro, ct) =>
    {
        ro.WithLocationUri(v => new Uri($"/api/refdata/brands/{v.Id}", UriKind.Relative));
        return _service.CreateBrandAsync(ro.Value, ct);
    }, cancellationToken: cancellationToken);

    [HttpPatch("{id}")]
    [Accepts<Brand>(HttpNames.MergePatchJsonMediaTypeName)]
    [ProducesResponseType(typeof(Brand), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> PatchAsync(string id, CancellationToken cancellationToken = default) => _webApi.PatchWithResultAsync<Brand>(Request,
        get: (ro, ct) => _service.GetBrandAsync(id.Required(), ct),
        put: (ro, ct) => _service.UpdateBrandAsync(id.Required(), ro.Value, ct),
        cancellationToken: cancellationToken);

    [HttpPost("{id}/activate")]
    [ProducesResponseType(typeof(Brand), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> ActivateAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.PostWithResultAsync<Brand>(Request, (_, ct) => _service.ActivateBrandAsync(id.Required(), ct), System.Net.HttpStatusCode.OK, cancellationToken: cancellationToken);

    [HttpPost("{id}/deactivate")]
    [ProducesResponseType(typeof(Brand), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> DeactivateAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.PostWithResultAsync<Brand>(Request, (_, ct) => _service.DeactivateBrandAsync(id.Required(), ct), System.Net.HttpStatusCode.OK, cancellationToken: cancellationToken);

    [HttpDelete("{id}")]
    [ProducesResponseType(204)]
    public Task<IActionResult> DeleteAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.DeleteWithResultAsync(Request, (_, ct) => _service.DeleteBrandAsync(id.Required(), ct), cancellationToken: cancellationToken);
}

#nullable restore
