// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.ContactMethod"/> to <see cref="Contracts.ContactMethod"/>.</summary>
internal partial class ContactMethodMapper : Mapper<Persistence.ContactMethod, Contracts.ContactMethod, ContactMethodMapper>
{
    /// <inheritdoc/>
    protected override Contracts.ContactMethod OnMap(Persistence.ContactMethod source)
    {
        var destination = new Contracts.ContactMethod
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.ContactMethod source, Contracts.ContactMethod destination);
}

#nullable restore