// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.CustomerType"/> to <see cref="Contracts.CustomerType"/>.</summary>
internal partial class CustomerTypeMapper : Mapper<Persistence.CustomerType, Contracts.CustomerType, CustomerTypeMapper>
{
    /// <inheritdoc/>
    protected override Contracts.CustomerType OnMap(Persistence.CustomerType source)
    {
        var destination = new Contracts.CustomerType
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.CustomerType source, Contracts.CustomerType destination);
}

#nullable restore