// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Orders.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Orders.Infrastructure.Repositories;

public partial class OrdersDbContext
{
    /// <summary>Adds the generated models to the <paramref name="modelBuilder"/>.</summary>
    /// <param name="modelBuilder">The <see cref="Microsoft.EntityFrameworkCore.ModelBuilder"/>.</param>
    public void AddGeneratedModels(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        // Add the entity/model configuration for the [Orders].[OrderStatus] database table.
        modelBuilder.Entity<Contoso.Orders.Infrastructure.Persistence.OrderStatus>(e =>
        {
            e.ToTable("OrderStatus", "Orders");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("OrderStatusId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Orders].[Order] database table.
        modelBuilder.Entity<Contoso.Orders.Infrastructure.Persistence.Order>(e =>
        {
            e.ToTable("Order", "Orders");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("OrderId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.CustomerId).HasColumnName("CustomerId").HasColumnType("NVARCHAR(100)");
            e.Property(p => p.StatusCode).HasColumnName("StatusCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
        });

        // Add the entity/model configuration for the [Orders].[OrderItem] database table.
        modelBuilder.Entity<Contoso.Orders.Infrastructure.Persistence.OrderItem>(e =>
        {
            e.ToTable("OrderItem", "Orders");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("OrderItemId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.OrderId).HasColumnName("OrderId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.ProductId).HasColumnName("ProductId").HasColumnType("NVARCHAR(100)");
            e.Property(p => p.Quantity).HasColumnName("Quantity").HasColumnType("DECIMAL(18, 4)");
            e.Property(p => p.UnitPrice).HasColumnName("UnitPrice").HasColumnType("DECIMAL(18, 4)");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Ignore(p => p.ETag);
        });
    }
}

#nullable restore