// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.Brand"/> to <see cref="Contracts.Brand"/>.</summary>
internal partial class BrandMapper : Mapper<Persistence.Brand, Contracts.Brand, BrandMapper>
{
    /// <inheritdoc/>
    protected override Contracts.Brand OnMap(Persistence.Brand source)
    {
        var destination = new Contracts.Brand
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.Brand source, Contracts.Brand destination);
}

#nullable restore