// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Contracts.Brand"/> to <see cref="Persistence.Brand"/>.</summary>
internal partial class BrandMapper : BiDirectionMapper<Contracts.Brand, Persistence.Brand, BrandMapper>
{
    /// <inheritdoc/>
    protected override Contracts.Brand OnMap(Persistence.Brand source)
    {
        var destination = new Contracts.Brand
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <b>To</b> mapping.</summary>
    partial void OnMapExtend(Persistence.Brand source, Contracts.Brand destination);

    /// <inheritdoc/>
    protected override Persistence.Brand OnMap(Contracts.Brand destination)
    {
        var source = new Persistence.Brand
        {
            Code = destination.Code!,
            Text = destination.Text,
            Description = destination.Description,
            SortOrder = destination.SortOrder,
            IsActive = !destination.IsInactive,
            StartsOn = destination.StartsOn,
            EndsOn = destination.EndsOn,
            ETag = destination.ETag
        };

        OnMapExtend(destination, source);
        return source;
    }

    /// <summary>Provides the opportunity to extend the <b>From</b> mapping.</summary>
    partial void OnMapExtend(Contracts.Brand destination, Persistence.Brand source);
}

#nullable restore
