// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Contracts.Category"/> to <see cref="Persistence.Category"/>.</summary>
internal partial class CategoryMapper : BiDirectionMapper<Contracts.Category, Persistence.Category, CategoryMapper>
{
    /// <inheritdoc/>
    protected override Contracts.Category OnMap(Persistence.Category source)
    {
        var destination = new Contracts.Category
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <b>To</b> mapping.</summary>
    partial void OnMapExtend(Persistence.Category source, Contracts.Category destination);

    /// <inheritdoc/>
    protected override Persistence.Category OnMap(Contracts.Category destination) => throw new NotSupportedException();
}

#nullable restore
