// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Mapping;

/// <summary>
/// Provides mapping from <see cref="Persistence.MovementStatus"/> to <see cref="Contracts.MovementStatus"/>.
/// </summary>
internal partial class MovementStatusMapper : Mapper<Persistence.MovementStatus, Contracts.MovementStatus, MovementStatusMapper>
{
    /// <inheritdoc/>
    protected override Contracts.MovementStatus OnMap(Persistence.MovementStatus source)
    {
        var destination = new Contracts.MovementStatus
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>
    /// Provides the opportunity to extend the <see cref="OnMap" /> method.
    /// </summary>
    partial void OnMapExtend(Persistence.MovementStatus source, Contracts.MovementStatus destination);
}

#nullable restore