// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Mapping;

/// <summary>
/// Provides mapping from <see cref="Persistence.MovementKind"/> to <see cref="Contracts.MovementKind"/>.
/// </summary>
internal partial class MovementKindMapper : Mapper<Persistence.MovementKind, Contracts.MovementKind, MovementKindMapper>
{
    /// <inheritdoc/>
    protected override Contracts.MovementKind OnMap(Persistence.MovementKind source)
    {
        var destination = new Contracts.MovementKind
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>
    /// Provides the opportunity to extend the <see cref="OnMap" /> method.
    /// </summary>
    partial void OnMapExtend(Persistence.MovementKind source, Contracts.MovementKind destination);
}

#nullable restore