// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Contracts.SubCategory"/> to <see cref="Persistence.SubCategory"/>.</summary>
internal partial class SubCategoryMapper : BiDirectionMapper<Contracts.SubCategory, Persistence.SubCategory, SubCategoryMapper>
{
    /// <inheritdoc/>
    protected override Contracts.SubCategory OnMap(Persistence.SubCategory source)
    {
        var destination = new Contracts.SubCategory
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag,
            CategoryCode = source.CategoryCode
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <b>To</b> mapping.</summary>
    partial void OnMapExtend(Persistence.SubCategory source, Contracts.SubCategory destination);

    /// <inheritdoc/>
    protected override Persistence.SubCategory OnMap(Contracts.SubCategory destination) => throw new NotSupportedException();
}

#nullable restore
