// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.UnitOfMeasure"/> to <see cref="Contracts.UnitOfMeasure"/>.</summary>
internal partial class UnitOfMeasureMapper : Mapper<Persistence.UnitOfMeasure, Contracts.UnitOfMeasure, UnitOfMeasureMapper>
{
    /// <inheritdoc/>
    protected override Contracts.UnitOfMeasure OnMap(Persistence.UnitOfMeasure source)
    {
        var destination = new Contracts.UnitOfMeasure
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag,
            Scale = source.Scale
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.UnitOfMeasure source, Contracts.UnitOfMeasure destination);
}

#nullable restore