

// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Api.Controllers;

/// <summary>Represents the <see cref="CustomerType"/> reference-data controller.</summary>
[ApiController, Route("/api/refdata/customer-types")]
[AllowAnonymous]
public partial class CustomerTypeController(CoreEx.AspNetCore.Mvc.WebApi webApi, IReferenceDataService service) : ControllerBase
{
    private readonly CoreEx.AspNetCore.Mvc.WebApi _webApi = webApi.ThrowIfNull();
    private readonly IReferenceDataService _service = service.ThrowIfNull();

    [HttpGet("{id}"), HttpHead("{id}")]
    [ProducesResponseType(typeof(CustomerType), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> GetAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.GetWithResultAsync(Request, (_, ct) => _service.GetCustomerTypeAsync(id.Required(), ct), cancellationToken: cancellationToken);

    [HttpPost]
    [Accepts<CustomerType>]
    [ProducesResponseType<CustomerType>(201)]
    [IdempotencyKey]
    public Task<IActionResult> CreateAsync(CancellationToken cancellationToken = default) => _webApi.PostWithResultAsync<CustomerType, CustomerType>(Request, (ro, ct) =>
    {
        ro.WithLocationUri(v => new Uri($"/api/refdata/customer-types/{v.Id}", UriKind.Relative));
        return _service.CreateCustomerTypeAsync(ro.Value, ct);
    }, cancellationToken: cancellationToken);

    [HttpPatch("{id}")]
    [Accepts<CustomerType>(HttpNames.MergePatchJsonMediaTypeName)]
    [ProducesResponseType(typeof(CustomerType), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> PatchAsync(string id, CancellationToken cancellationToken = default) => _webApi.PatchWithResultAsync<CustomerType>(Request,
        get: (ro, ct) => _service.GetCustomerTypeAsync(id.Required(), ct),
        put: (ro, ct) => _service.UpdateCustomerTypeAsync(id, ro.Value, ct),
        cancellationToken: cancellationToken);

    [HttpPut("{id}")]
    [Accepts<CustomerType>]
    [ProducesResponseType(typeof(CustomerType), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> PutAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.PutWithResultAsync<CustomerType, CustomerType>(Request, (ro, ct) => _service.UpdateCustomerTypeAsync(id.Required(), ro.Value, ct), cancellationToken: cancellationToken);

    [HttpPost("{id}/activate")]
    [ProducesResponseType(typeof(CustomerType), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> ActivateAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.PostWithResultAsync<CustomerType>(Request, (_, ct) => _service.ActivateCustomerTypeAsync(id.Required(), ct), System.Net.HttpStatusCode.OK, cancellationToken: cancellationToken);

    [HttpPost("{id}/deactivate")]
    [ProducesResponseType(typeof(CustomerType), 200)]
    [ProducesNotFoundProblem()]
    public Task<IActionResult> DeactivateAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.PostWithResultAsync<CustomerType>(Request, (_, ct) => _service.DeactivateCustomerTypeAsync(id.Required(), ct), System.Net.HttpStatusCode.OK, cancellationToken: cancellationToken);

    [HttpDelete("{id}")]
    [ProducesResponseType(204)]
    public Task<IActionResult> DeleteAsync(string id, CancellationToken cancellationToken = default)
        => _webApi.DeleteWithResultAsync(Request, (_, ct) => _service.DeleteCustomerTypeAsync(id.Required(), ct), cancellationToken: cancellationToken);
}

#nullable restore
