// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Contracts;

/// <summary>Represents the 'Contact Method' reference-data contract.</summary>
[ReferenceData]
public partial class ContactMethod : ReferenceData<ContactMethod> { }

/// <summary>
/// Represents the 'ContactMethod' reference-data contract collection.
/// </summary>
public partial class ContactMethodCollection() : ReferenceDataCollection<ContactMethod>(ReferenceDataSortOrder.Code) { }

#nullable restore