// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Contracts;

/// <summary>Represents the 'Customer Type' reference-data contract.</summary>
[ReferenceData]
public partial class CustomerType : ReferenceData<CustomerType> { }

/// <summary>
/// Represents the 'CustomerType' reference-data contract collection.
/// </summary>
public partial class CustomerTypeCollection() : ReferenceDataCollection<CustomerType>(ReferenceDataSortOrder.Code) { }

#nullable restore