// <auto-generated />

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Infrastructure.Persistence;

/// <summary>Cosmos persistence reference-data model representing the 'Customer Type'.</summary>
public partial class CustomerType : CosmosDbReferenceDataModelBase, ITypeDiscriminator
{
    /// <inheritdoc />
    public string? TypeDiscriminator { get; set; }
}

#nullable restore
