// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Persistence;

/// <summary>
/// Persistence reference-data model representing the '<c>[Shopping].[BasketStatus]</c>' database table.
/// </summary>
public partial class BasketStatus : ReferenceDataModelBase<string> { }

#nullable restore