// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Persistence;

/// <summary>Persistence reference-data model representing the '<c>[Shopping].[DiscountCoupon]</c>' database table.</summary>
public partial class DiscountCoupon : ReferenceDataModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>DiscountPercentage</c>' column (type '<c>DECIMAL(18, 2)</c>').</summary>
    public decimal DiscountPercentage { get; set; }
}

#nullable restore