// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Persistence;

/// <summary>
/// Persistence model representing the '<c>[Shopping].[Product]</c>' database table.
/// </summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>ProductId</c>' (type '<c>NVARCHAR(50)</c>').</remarks>
public partial class Product : ModelBase<string>
{
    /// <summary>
    /// Gets or sets the value of the '<c>Sku</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string Sku { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>Text</c>' column (type '<c>NVARCHAR(250)</c>').
    /// </summary>
    public string Text { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>UnitOfMeasureCode</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string UnitOfMeasureCode { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>Price</c>' column (type '<c>DECIMAL(18, 2)</c>').
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>IsInactive</c>' column (type '<c>BIT</c>').
    /// </summary>
    public bool IsInactive { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>IsNonStocked</c>' column (type '<c>BIT</c>').
    /// </summary>
    public bool IsNonStocked { get; set; }
}

#nullable restore