// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Application;

/// <summary>Provides the <see cref="IReferenceDataProvider"/> implementation.</summary>
[ScopedService]
public partial class ReferenceDataService(IReferenceDataRepository repository) : IReferenceDataProvider
{
    private readonly IReferenceDataRepository _repository = repository.ThrowIfNull();

    /// <inheritdoc/>
    public IEnumerable<(Type, Type)> Types =>
    [
        (typeof(BasketStatus), typeof(BasketStatusCollection)),
        (typeof(DiscountCoupon), typeof(DiscountCouponCollection)),
        (typeof(UnitOfMeasure), typeof(UnitOfMeasureCollection)),
    ];

    /// <inheritdoc/>
    public virtual async Task<IReferenceDataCollection> GetAsync(Type type, CancellationToken cancellationToken = default) => type switch
    {
        _ when type == typeof(BasketStatus) => await _repository.GetAllBasketStatusesAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(DiscountCoupon) => await _repository.GetAllDiscountCouponsAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(UnitOfMeasure) => await _repository.GetAllUnitsOfMeasureAsync(cancellationToken).ConfigureAwait(false),
        _ => throw new InvalidOperationException($"Type {type.FullName} is not a known {nameof(IReferenceData)}.")
    };
}

#nullable restore