CREATE OR ALTER PROCEDURE [Shopping].[spOutboxBatchCancel]
  @LeaseId UNIQUEIDENTIFIER,
  @BackoffSeconds INT
AS
BEGIN
  /*
   * This file is automatically generated by 'Contoso.Shopping.Database'; any changes will be lost.
   *
   * Cancels a batch by LeaseId, marking messages as pending with backoff and releasing the lease.
   * > Returns:
   *   0 = Success.
   *  -1 = No rows updated (e.g. already completed or invalid LeaseId).
   */

  SET NOCOUNT ON;
  SET XACT_ABORT ON;
  SET LOCK_TIMEOUT 5000; -- Milliseconds.
  SET TRANSACTION ISOLATION LEVEL READ COMMITTED

  DECLARE @Now DATETIME2 = SYSUTCDATETIME();

  BEGIN TRY
    BEGIN TRAN;

    -- 1) Cancel the batch.
    UPDATE o
      SET o.[Status] = 0,
          o.[Attempts] = o.[Attempts] + 1,
          o.[AvailableUtc] = DATEADD(SECOND, @BackoffSeconds, @Now),
          o.[LeaseId] = NULL,
          o.[LeaseUntilUtc] = NULL
    FROM [Shopping].[Outbox] AS o WITH (UPDLOCK, ROWLOCK)
    WHERE o.[LeaseId] = @LeaseId
      AND o.[Status] = 1;

    IF (@@ROWCOUNT = 0)
    BEGIN
      COMMIT;
      RETURN -1; -- No rows updated.
    END

    COMMIT;

    -- 2) Release the partition lease.
    BEGIN TRY
      EXEC [Shopping].[spOutboxLeaseRelease] @LeaseId;
    END TRY
    BEGIN CATCH
      -- Ignore: lease will expire. Don't fail cancel.
    END CATCH

    RETURN 0;
  END TRY
  BEGIN CATCH
    IF (XACT_STATE() <> 0) ROLLBACK;
    THROW; -- Re-throw preserves error details to caller.
  END CATCH
END
