// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Application.Repositories;

/// <summary>Enables the underlying reference-data repository.</summary>
public partial interface IReferenceDataRepository
{
    /// <summary>Gets all <see cref="BasketStatus"/> items.</summary>
    Task<BasketStatusCollection> GetAllBasketStatusesAsync(CancellationToken cancellationToken = default);

    /// <summary>Gets all <see cref="DiscountCoupon"/> items.</summary>
    Task<DiscountCouponCollection> GetAllDiscountCouponsAsync(CancellationToken cancellationToken = default);

    /// <summary>Gets all <see cref="UnitOfMeasure"/> items.</summary>
    Task<UnitOfMeasureCollection> GetAllUnitsOfMeasureAsync(CancellationToken cancellationToken = default);
}
    
#nullable restore
