// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Infrastructure.Repositories;

/// <summary>Provides the underlying reference-data repository.</summary>
[ScopedService<IReferenceDataRepository>]
public partial class ReferenceDataRepository : IReferenceDataRepository
{
    /// <inheritdoc/>
    public Task<Contracts.CustomerTypeCollection> GetAllCustomerTypesAsync(CancellationToken cancellationToken = default)
        => _cosmos.CustomerTypes.Query().ToMappedItemsAsync<Contracts.CustomerTypeCollection, Contracts.CustomerType>(CustomerTypeMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.ContactMethodCollection> GetAllContactMethodsAsync(CancellationToken cancellationToken = default)
        => _cosmos.ContactMethods.Query().ToMappedItemsAsync<Contracts.ContactMethodCollection, Contracts.ContactMethod>(ContactMethodMapper.Map, cancellationToken);
}

#nullable restore
