/*
 * WARNING: This file is currently in an initial scaffolding state and will be (replaced) generated by 'app-name.CodeGen' in the future; any changes will be lost.
 */

namespace app-name.Application;

/// <summary>Provides the <see cref="IReferenceDataProvider"/> implementation.</summary>
[ScopedService<IReferenceDataProvider>]
public partial class ReferenceDataService(IReferenceDataRepository repository) : IReferenceDataProvider
{
    private readonly IReferenceDataRepository _repository = repository.ThrowIfNull();

    /// <inheritdoc/>
    public IEnumerable<(Type, Type)> Types => [];

    /// <inheritdoc/>
    public virtual Task<IReferenceDataCollection> GetAsync(Type type, CancellationToken cancellationToken = default) => throw new NotImplementedException();
}
