// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Application;

/// <summary>Enables the <see cref="IReferenceData"/> mutable services.</summary>
public partial interface IReferenceDataService
{
    #region Brand

    /// <summary>Gets the specified <see cref="Brand"/>.</summary>
    Task<Result<Brand>> GetBrandAsync(string id, CancellationToken cancellationToken);

    /// <summary>Creates the specified <see cref="Brand"/>.</summary>
    Task<Result<Brand>> CreateBrandAsync(Brand value, CancellationToken cancellationToken);

    /// <summary>Updates the specified <see cref="Brand"/>.</summary>
    Task<Result<Brand>> UpdateBrandAsync(string id, Brand value, CancellationToken cancellationToken);

    /// <summary>Activates the specified <see cref="Brand"/>.</summary>
    Task<Result<Brand>> ActivateBrandAsync(string id, CancellationToken cancellationToken);

    /// <summary>Deactivates the specified <see cref="Brand"/>.</summary>
    Task<Result<Brand>> DeactivateBrandAsync(string id, CancellationToken cancellationToken);

    /// <summary>Deletes the specified <see cref="Brand"/>.</summary>
    Task<Result> DeleteBrandAsync(string id, CancellationToken cancellationToken);

    #endregion
}

#nullable restore
