// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Mapping;

/// <summary>
/// Provides mapping from <see cref="Persistence.BasketStatus"/> to <see cref="Contracts.BasketStatus"/>.
/// </summary>
internal partial class BasketStatusMapper : Mapper<Persistence.BasketStatus, Contracts.BasketStatus, BasketStatusMapper>
{
    /// <inheritdoc/>
    protected override Contracts.BasketStatus OnMap(Persistence.BasketStatus source)
    {
        var destination = new Contracts.BasketStatus
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>
    /// Provides the opportunity to extend the <see cref="OnMap" /> method.
    /// </summary>
    partial void OnMapExtend(Persistence.BasketStatus source, Contracts.BasketStatus destination);
}

#nullable restore