// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Contracts.BasketStatus"/> to <see cref="Persistence.BasketStatus"/>.</summary>
internal partial class BasketStatusMapper : BiDirectionMapper<Contracts.BasketStatus, Persistence.BasketStatus, BasketStatusMapper>
{
    /// <inheritdoc/>
    protected override Contracts.BasketStatus OnMap(Persistence.BasketStatus source)
    {
        var destination = new Contracts.BasketStatus
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <b>To</b> mapping.</summary>
    partial void OnMapExtend(Persistence.BasketStatus source, Contracts.BasketStatus destination);

    /// <inheritdoc/>
    protected override Persistence.BasketStatus OnMap(Contracts.BasketStatus destination) => throw new NotSupportedException();
}

#nullable restore
