// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.DiscountCoupon"/> to <see cref="Contracts.DiscountCoupon"/>.</summary>
internal partial class DiscountCouponMapper : Mapper<Persistence.DiscountCoupon, Contracts.DiscountCoupon, DiscountCouponMapper>
{
    /// <inheritdoc/>
    protected override Contracts.DiscountCoupon OnMap(Persistence.DiscountCoupon source)
    {
        var destination = new Contracts.DiscountCoupon
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag,
            DiscountPercentage = source.DiscountPercentage
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.DiscountCoupon source, Contracts.DiscountCoupon destination);
}

#nullable restore