// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Contracts.UnitOfMeasure"/> to <see cref="Persistence.UnitOfMeasure"/>.</summary>
internal partial class UnitOfMeasureMapper : BiDirectionMapper<Contracts.UnitOfMeasure, Persistence.UnitOfMeasure, UnitOfMeasureMapper>
{
    /// <inheritdoc/>
    protected override Contracts.UnitOfMeasure OnMap(Persistence.UnitOfMeasure source)
    {
        var destination = new Contracts.UnitOfMeasure
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag,
            Scale = source.Scale
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <b>To</b> mapping.</summary>
    partial void OnMapExtend(Persistence.UnitOfMeasure source, Contracts.UnitOfMeasure destination);

    /// <inheritdoc/>
    protected override Persistence.UnitOfMeasure OnMap(Contracts.UnitOfMeasure destination) => throw new NotSupportedException();
}

#nullable restore
