// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Contracts;

/// <summary>Represents the 'Basket Status' reference-data contract.</summary>
[ReferenceData]
public partial class BasketStatus : ReferenceData<BasketStatus> { }

/// <summary>
/// Represents the 'BasketStatus' reference-data contract collection.
/// </summary>
public partial class BasketStatusCollection() : ReferenceDataCollection<BasketStatus>(ReferenceDataSortOrder.Code) { }

#nullable restore