// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Contracts;

/// <summary>
/// Represents the 'Discount Coupon' reference-data contract.
/// </summary>
[ReferenceData]
public partial class DiscountCoupon : ReferenceData<DiscountCoupon> { }

/// <summary>
/// Represents the 'DiscountCoupon' reference-data contract collection.
/// </summary>
public partial class DiscountCouponCollection() : ReferenceDataCollection<DiscountCoupon>(ReferenceDataSortOrder.Code) { }

#nullable restore