// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Contracts;

/// <summary>
/// Represents the 'Unit Of Measure' reference-data contract.
/// </summary>
[ReferenceData]
public partial class UnitOfMeasure : ReferenceData<UnitOfMeasure> 
{
    /// <summary>
    /// Gets or initializes the Scale.
    /// </summary>
    public int Scale { get; init; } = default!;
}

/// <summary>
/// Represents the 'UnitOfMeasure' reference-data contract collection.
/// </summary>
public partial class UnitOfMeasureCollection() : ReferenceDataCollection<UnitOfMeasure>(ReferenceDataSortOrder.Code) { }

#nullable restore