// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>
/// Persistence reference-data model representing the '<c>"products"."category"</c>' database table.
/// </summary>
public partial class Category : ReferenceDataModelBase<string> { }

#nullable restore