// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>Persistence model representing the '<c>"products"."inventory"</c>' database table.</summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>inventory_id</c>' (type '<c>CHARACTER VARYING(50)</c>').</remarks>
public partial class Inventory : ModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>qty_on_hand</c>' column (type '<c>NUMERIC(18, 2)</c>').</summary>
    public decimal QtyOnHand { get; set; }
}

#nullable restore