// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>
/// Persistence model representing the '<c>[Products].[Inventory]</c>' database table.
/// </summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>InventoryId</c>' (type '<c>NVARCHAR(50)</c>').</remarks>
public partial class Inventory : ModelBase<string>
{
    /// <summary>
    /// Gets or sets the value of the '<c>QtyOnHand</c>' column (type '<c>DECIMAL(18, 2)</c>').
    /// </summary>
    public decimal QtyOnHand { get; set; }
}

#nullable restore