// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>Persistence model representing the '<c>"products"."movement"</c>' database table.</summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>movement_id</c>' (type '<c>CHARACTER VARYING(50)</c>').</remarks>
public partial class Movement : ModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>reference_id</c>' column (type '<c>CHARACTER VARYING(50)</c>').</summary>
    public string ReferenceId { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>movement_kind_code</c>' column (type '<c>CHARACTER VARYING(50)</c>').</summary>
    public string MovementKindCode { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>movement_status_code</c>' column (type '<c>CHARACTER VARYING(50)</c>').</summary>
    public string MovementStatusCode { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>product_id</c>' column (type '<c>CHARACTER VARYING(50)</c>').</summary>
    public string ProductId { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>quantity</c>' column (type '<c>NUMERIC(18, 2)</c>').</summary>
    public decimal Quantity { get; set; }

    /// <summary>Gets or sets the value of the '<c>unit_of_measure_code</c>' column (type '<c>CHARACTER VARYING(50)</c>').</summary>
    public string UnitOfMeasureCode { get; set; } = default!;
}

#nullable restore