// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>
/// Persistence reference-data model representing the '<c>[Products].[MovementStatus]</c>' database table.
/// </summary>
public partial class MovementStatus : ReferenceDataModelBase<string> { }

#nullable restore