// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>
/// Persistence model representing the '<c>[Products].[Movement]</c>' database table.
/// </summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>MovementId</c>' (type '<c>NVARCHAR(50)</c>').</remarks>
public partial class Movement : ModelBase<string>
{
    /// <summary>
    /// Gets or sets the value of the '<c>ReferenceId</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string ReferenceId { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>MovementKindCode</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string MovementKindCode { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>MovementStatusCode</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string MovementStatusCode { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>ProductId</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string ProductId { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>Quantity</c>' column (type '<c>DECIMAL(18, 2)</c>').
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>UnitOfMeasureCode</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string UnitOfMeasureCode { get; set; } = default!;
}

#nullable restore