// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>
/// Persistence model representing the '<c>"products"."product"</c>' database table.
/// </summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>product_id</c>' (type '<c>CHARACTER VARYING(50)</c>').</remarks>
public partial class Product : ModelBase<string>, ILogicallyDeleted
{
    /// <summary>
    /// Gets or sets the value of the '<c>sku</c>' column (type '<c>CHARACTER VARYING(50)</c>').
    /// </summary>
    public string Sku { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>text</c>' column (type '<c>CHARACTER VARYING(250)</c>').
    /// </summary>
    public string Text { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>sub_category_code</c>' column (type '<c>CHARACTER VARYING(50)</c>').
    /// </summary>
    public string SubCategoryCode { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>unit_of_measure_code</c>' column (type '<c>CHARACTER VARYING(50)</c>').
    /// </summary>
    public string UnitOfMeasureCode { get; set; } = default!;

    /// <summary>
    /// Gets or sets the value of the '<c>brand_code</c>' column (type '<c>CHARACTER VARYING(50) NULL</c>').
    /// </summary>
    public string? BrandCode { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>price</c>' column (type '<c>NUMERIC(18, 2)</c>').
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>is_inactive</c>' column (type '<c>BOOLEAN</c>').
    /// </summary>
    public bool IsInactive { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>is_non_stocked</c>' column (type '<c>BOOLEAN</c>').
    /// </summary>
    public bool IsNonStocked { get; set; }

    /// <summary>
    /// Gets or sets the value of the '<c>is_deleted</c>' column (type '<c>BOOLEAN</c>'); see <see cref="ILogicallyDeleted.IsDeleted"/>.
    /// </summary>
    public bool IsDeleted { get; set; }
}

#nullable restore