// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>
/// Persistence reference-data model representing the '<c>[Products].[SubCategory]</c>' database table.
/// </summary>
public partial class SubCategory : ReferenceDataModelBase<string>
{
    /// <summary>
    /// Gets or sets the value of the '<c>CategoryCode</c>' column (type '<c>NVARCHAR(50)</c>').
    /// </summary>
    public string CategoryCode { get; set; } = default!;
}

#nullable restore