// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Persistence;

/// <summary>
/// Persistence reference-data model representing the '<c>"products"."unit_of_measure"</c>' database table.
/// </summary>
public partial class UnitOfMeasure : ReferenceDataModelBase<string>
{
    /// <summary>
    /// Gets or sets the value of the '<c>scale</c>' column (type '<c>INTEGER</c>').
    /// </summary>
    public int Scale { get; set; }
}

#nullable restore