// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Repositories;

/// <summary>Provides the underlying reference-data repository.</summary>
[ScopedService<IReferenceDataRepository>]
public partial class ReferenceDataRepository : IReferenceDataRepository
{
    /// <inheritdoc/>
    public Task<Contracts.BasketStatusCollection> GetAllBasketStatusesAsync(CancellationToken cancellationToken = default)
        => _ef.ThrowIfNull().Model<Persistence.BasketStatus>().Query().ToMappedItemsAsync<Persistence.BasketStatus, Contracts.BasketStatusCollection, Contracts.BasketStatus>(BasketStatusMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.DiscountCouponCollection> GetAllDiscountCouponsAsync(CancellationToken cancellationToken = default)
        => _ef.ThrowIfNull().Model<Persistence.DiscountCoupon>().Query().ToMappedItemsAsync<Persistence.DiscountCoupon, Contracts.DiscountCouponCollection, Contracts.DiscountCoupon>(DiscountCouponMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.UnitOfMeasureCollection> GetAllUnitsOfMeasureAsync(CancellationToken cancellationToken = default)
        => _ef.ThrowIfNull().Model<Persistence.UnitOfMeasure>().Query().ToMappedItemsAsync<Persistence.UnitOfMeasure, Contracts.UnitOfMeasureCollection, Contracts.UnitOfMeasure>(UnitOfMeasureMapper.Map, cancellationToken);
}

#nullable restore