// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Infrastructure.Repositories;

public partial class ShoppingDbContext
{
    /// <summary>Adds the generated models to the <paramref name="modelBuilder"/>.</summary>
    /// <param name="modelBuilder">The <see cref="Microsoft.EntityFrameworkCore.ModelBuilder"/>.</param>
    public void AddGeneratedModels(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        // Add the entity/model configuration for the [Shopping].[BasketStatus] database table.
        modelBuilder.Entity<Contoso.Shopping.Infrastructure.Persistence.BasketStatus>(e =>
        {
            e.ToTable("BasketStatus", "Shopping");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("BasketStatusId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Shopping].[DiscountCoupon] database table.
        modelBuilder.Entity<Contoso.Shopping.Infrastructure.Persistence.DiscountCoupon>(e =>
        {
            e.ToTable("DiscountCoupon", "Shopping");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("DiscountCouponId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.DiscountPercentage).HasColumnName("DiscountPercentage").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.StartsOn).HasColumnName("StartsOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.EndsOn).HasColumnName("EndsOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description);
        });

        // Add the entity/model configuration for the [Shopping].[UnitOfMeasure] database table.
        modelBuilder.Entity<Contoso.Shopping.Infrastructure.Persistence.UnitOfMeasure>(e =>
        {
            e.ToTable("UnitOfMeasure", "Shopping");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("UnitOfMeasureId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.Scale).HasColumnName("Scale").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Shopping].[Basket] database table.
        modelBuilder.Entity<Contoso.Shopping.Infrastructure.Persistence.Basket>(e =>
        {
            e.ToTable("Basket", "Shopping");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("BasketId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.CustomerId).HasColumnName("CustomerId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.BasketStatusCode).HasColumnName("BasketStatusCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.SubTotal).HasColumnName("SubTotal").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.DiscountCouponCode).HasColumnName("DiscountCouponCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.DiscountAmount).HasColumnName("DiscountAmount").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.Total).HasColumnName("Total").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
        });

        // Add the entity/model configuration for the [Shopping].[BasketItem] database table.
        modelBuilder.Entity<Contoso.Shopping.Infrastructure.Persistence.BasketItem>(e =>
        {
            e.ToTable("BasketItem", "Shopping");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("BasketItemId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.BasketId).HasColumnName("BasketId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.ProductId).HasColumnName("ProductId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Sku).HasColumnName("Sku").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UnitOfMeasureCode).HasColumnName("UnitOfMeasureCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.UnitPrice).HasColumnName("UnitPrice").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.Quantity).HasColumnName("Quantity").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.CreatedBy).Ignore(p => p.CreatedOn).Ignore(p => p.UpdatedBy).Ignore(p => p.UpdatedOn);
        });

        // Add the entity/model configuration for the [Shopping].[Product] database table.
        modelBuilder.Entity<Contoso.Shopping.Infrastructure.Persistence.Product>(e =>
        {
            e.ToTable("Product", "Shopping");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("ProductId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Sku).HasColumnName("Sku").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UnitOfMeasureCode).HasColumnName("UnitOfMeasureCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Price).HasColumnName("Price").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.IsInactive).HasColumnName("IsInactive").HasColumnType("BIT");
            e.Property(p => p.IsNonStocked).HasColumnName("IsNonStocked").HasColumnType("BIT");
            e.Ignore(p => p.CreatedBy).Ignore(p => p.CreatedOn).Ignore(p => p.UpdatedBy).Ignore(p => p.UpdatedOn).Ignore(p => p.ETag);
        });
    }
}

#nullable restore