// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Application;

/// <summary>Enables the <see cref="IReferenceData"/> mutable services.</summary>
public partial interface IReferenceDataService
{
    #region CustomerType

    /// <summary>Gets the specified <see cref="CustomerType"/>.</summary>
    Task<Result<CustomerType>> GetCustomerTypeAsync(string id, CancellationToken cancellationToken);

    /// <summary>Creates the specified <see cref="CustomerType"/>.</summary>
    Task<Result<CustomerType>> CreateCustomerTypeAsync(CustomerType value, CancellationToken cancellationToken);

    /// <summary>Updates the specified <see cref="CustomerType"/>.</summary>
    Task<Result<CustomerType>> UpdateCustomerTypeAsync(string id, CustomerType value, CancellationToken cancellationToken);

    /// <summary>Activates the specified <see cref="CustomerType"/>.</summary>
    Task<Result<CustomerType>> ActivateCustomerTypeAsync(string id, CancellationToken cancellationToken);

    /// <summary>Deactivates the specified <see cref="CustomerType"/>.</summary>
    Task<Result<CustomerType>> DeactivateCustomerTypeAsync(string id, CancellationToken cancellationToken);

    /// <summary>Deletes the specified <see cref="CustomerType"/>.</summary>
    Task<Result> DeleteCustomerTypeAsync(string id, CancellationToken cancellationToken);

    #endregion
}

#nullable restore
