// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Api.Controllers;

/// <summary>
/// Represents the reference-data controller.
/// </summary>
[ApiController, Route("/api/refdata")]
public partial class ReferenceDataController(CoreEx.AspNetCore.Mvc.WebApi webApi) : ControllerBase
{
    private readonly CoreEx.AspNetCore.Mvc.WebApi _webApi = webApi.ThrowIfNull();

    private static readonly DataMap<string> _mapper = new(StringComparer.OrdinalIgnoreCase)
    {
        { "basket-statuses", nameof(BasketStatus) },
        { "discount-coupons", nameof(DiscountCoupon) },
        { "units-of-measure", nameof(UnitOfMeasure) }
    };

    [HttpGet("basket-statuses"), HttpHead("basket-statuses")]
    [ProducesResponseType(typeof(BasketStatus[]), 200)]
    public Task<IActionResult> GetBasketStatusesAsync([FromQuery] IEnumerable<string>? codes = default, string? text = default)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetWithFilterAsync<BasketStatus>(codes, text, ro.IsIncludeInactive, ct));

    [HttpGet("discount-coupons"), HttpHead("discount-coupons")]
    [ProducesResponseType(typeof(DiscountCoupon[]), 200)]
    public Task<IActionResult> GetDiscountCouponsAsync([FromQuery] IEnumerable<string>? codes = default, string? text = default)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetWithFilterAsync<DiscountCoupon>(codes, text, ro.IsIncludeInactive, ct));

    [HttpGet("units-of-measure"), HttpHead("units-of-measure")]
    [ProducesResponseType(typeof(UnitOfMeasure[]), 200)]
    public Task<IActionResult> GetUnitsOfMeasureAsync([FromQuery] IEnumerable<string>? codes = default, string? text = default)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetWithFilterAsync<UnitOfMeasure>(codes, text, ro.IsIncludeInactive, ct));

    [HttpGet]
    [ProducesResponseType(typeof(ReferenceDataMultiDictionary), 200)]
    public Task<IActionResult> GetNamedAsync([FromQuery] string[] name)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetNamedAsync(name, ro.IsIncludeInactive, _mapper, ct));
}

#nullable restore