// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Shopping.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Shopping.Api.Controllers;

/// <summary>Represents the reference-data controller.</summary>
[ApiController, Route("/api/refdata")]
public partial class ReferenceDataController(CoreEx.AspNetCore.Mvc.WebApi webApi) : ControllerBase
{
    private readonly CoreEx.AspNetCore.Mvc.WebApi _webApi = webApi.ThrowIfNull();

    [HttpGet("basket-statuses"), HttpHead("basket-statuses")]
    [ProducesResponseType(typeof(BasketStatus[]), 200)]
    [Query(supportsOrderBy: true), Paging(supportsCount: true)]
    public Task<IActionResult> GetBasketStatusesAsync() => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.QueryAsync<BasketStatus>(ro.QueryArgs, ro.PagingArgs, ct));

    [HttpGet("discount-coupons"), HttpHead("discount-coupons")]
    [ProducesResponseType(typeof(DiscountCoupon[]), 200)]
    [Query(supportsOrderBy: true), Paging(supportsCount: true)]
    public Task<IActionResult> GetDiscountCouponsAsync() => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.QueryAsync<DiscountCoupon>(ro.QueryArgs, ro.PagingArgs, ct));

    [HttpGet("units-of-measure"), HttpHead("units-of-measure")]
    [ProducesResponseType(typeof(UnitOfMeasure[]), 200)]
    [Query(supportsOrderBy: true), Paging(supportsCount: true)]
    public Task<IActionResult> GetUnitsOfMeasureAsync() => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.QueryAsync<UnitOfMeasure>(ro.QueryArgs, ro.PagingArgs, ct));

    [HttpGet]
    [ProducesResponseType(typeof(ReferenceDataMultiDictionary), 200)]
    public Task<IActionResult> GetNamedAsync([FromQuery] string[] name) => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetNamedAsync(name, ro.IsIncludeInactive, ct));
}

#nullable restore
