// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Application;

/// <summary>Provides the <see cref="IReferenceDataProvider"/> implementation.</summary>
[ScopedService]
public partial class ReferenceDataService(IReferenceDataRepository repository) : IReferenceDataProvider
{
    private readonly IReferenceDataRepository _repository = repository.ThrowIfNull();

    /// <inheritdoc/>
    public IEnumerable<(Type, Type)> Types =>
    [
        (typeof(Brand), typeof(BrandCollection)),
        (typeof(Category), typeof(CategoryCollection)),
        (typeof(MovementKind), typeof(MovementKindCollection)),
        (typeof(MovementStatus), typeof(MovementStatusCollection)),
        (typeof(SubCategory), typeof(SubCategoryCollection)),
        (typeof(UnitOfMeasure), typeof(UnitOfMeasureCollection)),
    ];

    /// <inheritdoc/>
    public virtual async Task<IReferenceDataCollection> GetAsync(Type type, CancellationToken cancellationToken = default) => type switch
    {
        _ when type == typeof(Brand) => await _repository.GetAllBrandsAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(Category) => await _repository.GetAllCategoriesAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(MovementKind) => await _repository.GetAllMovementKindsAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(MovementStatus) => await _repository.GetAllMovementStatusesAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(SubCategory) => await _repository.GetAllSubCategoriesAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(UnitOfMeasure) => await _repository.GetAllUnitsOfMeasureAsync(cancellationToken).ConfigureAwait(false),
        _ => throw new InvalidOperationException($"Type {type.FullName} is not a known {nameof(IReferenceData)}.")
    };
}

#nullable restore