// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Orders.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Orders.Infrastructure.Persistence;

/// <summary>
/// Persistence reference-data model representing the '<c>[Orders].[OrderStatus]</c>' database table.
/// </summary>
public partial class OrderStatus : ReferenceDataModelBase<string> { }

#nullable restore