// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Orders.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Orders.Infrastructure.Persistence;

/// <summary>Persistence model representing the '<c>[Orders].[OrderItem]</c>' database table.</summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>OrderItemId</c>' (type '<c>NVARCHAR(50)</c>').</remarks>
public partial class OrderItem : ModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>OrderId</c>' column (type '<c>NVARCHAR(50)</c>').</summary>
    public string OrderId { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>ProductId</c>' column (type '<c>NVARCHAR(100)</c>').</summary>
    public string ProductId { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>Quantity</c>' column (type '<c>DECIMAL(18, 4)</c>').</summary>
    public decimal Quantity { get; set; }

    /// <summary>Gets or sets the value of the '<c>UnitPrice</c>' column (type '<c>DECIMAL(18, 4)</c>').</summary>
    public decimal UnitPrice { get; set; }
}

#nullable restore