<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="UnitTestEx.NUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CoreEx.UnitTesting\CoreEx.UnitTesting.csproj" />
    <ProjectReference Include="..\..\src\Contoso.Customers.Application\Contoso.Customers.Application.csproj" />
    <ProjectReference Include="..\..\src\Contoso.Customers.Contracts\Contoso.Customers.Contracts.csproj" />
    <ProjectReference Include="..\Contoso.Customers.Test.Common\Contoso.Customers.Test.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
