// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Application.Repositories;

/// <summary>Enables the underlying reference-data repository.</summary>
public partial interface IReferenceDataRepository
{
    /// <summary>Gets all <see cref="CustomerType"/> items.</summary>
    /// <returns>The <see cref="CustomerTypeCollection"/>.</returns>
    Task<CustomerTypeCollection> GetAllCustomerTypesAsync(CancellationToken cancellationToken = default);

    /// <summary>Gets all <see cref="ContactMethod"/> items.</summary>
    /// <returns>The <see cref="ContactMethodCollection"/>.</returns>
    Task<ContactMethodCollection> GetAllContactMethodsAsync(CancellationToken cancellationToken = default);
}
    
#nullable restore