// <auto-generated />

/*
 * This file is automatically generated; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Repositories;

public partial class ProductsDbContext
{
    /// <summary>
    /// Adds the generated models to the <paramref name="modelBuilder"/>.
    /// </summary>
    /// <param name="modelBuilder">The <see cref="Microsoft.EntityFrameworkCore.ModelBuilder"/>.</param>
    public void AddGeneratedModels(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        // Add the entity/model configuration for the [Products].[Brand] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Brand>(e =>
        {
            e.ToTable("Brand", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("BrandId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Products].[Category] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Category>(e =>
        {
            e.ToTable("Category", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("CategoryId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Products].[MovementKind] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.MovementKind>(e =>
        {
            e.ToTable("MovementKind", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("MovementKindId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Products].[MovementStatus] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.MovementStatus>(e =>
        {
            e.ToTable("MovementStatus", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("MovementStatusId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Products].[SubCategory] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.SubCategory>(e =>
        {
            e.ToTable("SubCategory", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("SubCategoryId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.CategoryCode).HasColumnName("CategoryCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Products].[UnitOfMeasure] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.UnitOfMeasure>(e =>
        {
            e.ToTable("UnitOfMeasure", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("UnitOfMeasureId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Code).HasColumnName("Code").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.IsActive).HasColumnName("IsActive").HasColumnType("BIT");
            e.Property(p => p.SortOrder).HasColumnName("SortOrder").HasColumnType("INT");
            e.Property(p => p.Scale).HasColumnName("Scale").HasColumnType("INT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the [Products].[Inventory] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Inventory>(e =>
        {
            e.ToTable("Inventory", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("InventoryId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.QtyOnHand).HasColumnName("QtyOnHand").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.CreatedBy).Ignore(p => p.CreatedOn).Ignore(p => p.UpdatedBy).Ignore(p => p.UpdatedOn);
        });

        // Add the entity/model configuration for the [Products].[Movement] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Movement>(e =>
        {
            e.ToTable("Movement", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("MovementId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.ReferenceId).HasColumnName("ReferenceId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.MovementKindCode).HasColumnName("MovementKindCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.MovementStatusCode).HasColumnName("MovementStatusCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.ProductId).HasColumnName("ProductId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Quantity).HasColumnName("Quantity").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.UnitOfMeasureCode).HasColumnName("UnitOfMeasureCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
        });

        // Add the entity/model configuration for the [Products].[Product] database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Product>(e =>
        {
            e.ToTable("Product", "Products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("ProductId").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Sku).HasColumnName("Sku").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Text).HasColumnName("Text").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.SubCategoryCode).HasColumnName("SubCategoryCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.UnitOfMeasureCode).HasColumnName("UnitOfMeasureCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.BrandCode).HasColumnName("BrandCode").HasColumnType("NVARCHAR(50)");
            e.Property(p => p.Price).HasColumnName("Price").HasColumnType("DECIMAL(18, 2)");
            e.Property(p => p.IsInactive).HasColumnName("IsInactive").HasColumnType("BIT");
            e.Property(p => p.IsNonStocked).HasColumnName("IsNonStocked").HasColumnType("BIT");
            e.Property(p => p.CreatedBy).HasColumnName("CreatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.CreatedOn).HasColumnName("CreatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.UpdatedBy).HasColumnName("UpdatedBy").HasColumnType("NVARCHAR(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("UpdatedOn").HasColumnType("DATETIMEOFFSET");
            e.Property(p => p.ETag).HasColumnName("RowVersion").HasColumnType("TIMESTAMP").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, byte[]>(BaseDatabase.RowVersionConverter));
            e.Property(p => p.IsDeleted).HasColumnName("IsDeleted").HasColumnType("BIT");
        });
    }
}

#nullable restore