// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.Database'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Repositories;

public partial class ProductsDbContext
{
    /// <summary>
    /// Adds the generated models to the <paramref name="modelBuilder"/>.
    /// </summary>
    /// <param name="modelBuilder">The <see cref="Microsoft.EntityFrameworkCore.ModelBuilder"/>.</param>
    public void AddGeneratedModels(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        // Add the entity/model configuration for the "products"."brand" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Brand>(e =>
        {
            e.ToTable("brand", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("brand_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "products"."category" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Category>(e =>
        {
            e.ToTable("category", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("category_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "products"."movement_kind" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.MovementKind>(e =>
        {
            e.ToTable("movement_kind", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("movement_kind_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "products"."movement_status" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.MovementStatus>(e =>
        {
            e.ToTable("movement_status", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("movement_status_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "products"."sub_category" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.SubCategory>(e =>
        {
            e.ToTable("sub_category", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("sub_category_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.CategoryCode).HasColumnName("category_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "products"."unit_of_measure" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.UnitOfMeasure>(e =>
        {
            e.ToTable("unit_of_measure", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("unit_of_measure_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.Scale).HasColumnName("scale").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "products"."inventory" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Inventory>(e =>
        {
            e.ToTable("inventory", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("inventory_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.QtyOnHand).HasColumnName("qty_on_hand").HasColumnType("NUMERIC(18, 2)");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.CreatedBy).Ignore(p => p.CreatedOn).Ignore(p => p.UpdatedBy).Ignore(p => p.UpdatedOn);
        });

        // Add the entity/model configuration for the "products"."movement" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Movement>(e =>
        {
            e.ToTable("movement", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("movement_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.ReferenceId).HasColumnName("reference_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.MovementKindCode).HasColumnName("movement_kind_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.MovementStatusCode).HasColumnName("movement_status_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.ProductId).HasColumnName("product_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Quantity).HasColumnName("quantity").HasColumnType("NUMERIC(18, 2)");
            e.Property(p => p.UnitOfMeasureCode).HasColumnName("unit_of_measure_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
        });

        // Add the entity/model configuration for the "products"."product" database table.
        modelBuilder.Entity<Contoso.Products.Infrastructure.Persistence.Product>(e =>
        {
            e.ToTable("product", "products");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("product_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Sku).HasColumnName("sku").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.SubCategoryCode).HasColumnName("sub_category_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.UnitOfMeasureCode).HasColumnName("unit_of_measure_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.BrandCode).HasColumnName("brand_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Price).HasColumnName("price").HasColumnType("NUMERIC(18, 2)");
            e.Property(p => p.IsInactive).HasColumnName("is_inactive").HasColumnType("BOOLEAN");
            e.Property(p => p.IsNonStocked).HasColumnName("is_non_stocked").HasColumnType("BOOLEAN");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Property(p => p.IsDeleted).HasColumnName("is_deleted").HasColumnType("BOOLEAN");
        });
    }
}

#nullable restore