// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Products.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Products.Infrastructure.Repositories;

/// <summary>Provides the underlying reference-data repository.</summary>
[ScopedService<IReferenceDataRepository>]
public partial class ReferenceDataRepository : IReferenceDataRepository
{
    /// <inheritdoc/>
    public Task<Contracts.BrandCollection> GetAllBrandsAsync(CancellationToken cancellationToken = default)
        => ef.ThrowIfNull().Model<Persistence.Brand>().Query().ToMappedItemsAsync<Persistence.Brand, Contracts.BrandCollection, Contracts.Brand>(BrandMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.CategoryCollection> GetAllCategoriesAsync(CancellationToken cancellationToken = default)
        => ef.ThrowIfNull().Model<Persistence.Category>().Query().ToMappedItemsAsync<Persistence.Category, Contracts.CategoryCollection, Contracts.Category>(CategoryMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.MovementKindCollection> GetAllMovementKindsAsync(CancellationToken cancellationToken = default)
        => ef.ThrowIfNull().Model<Persistence.MovementKind>().Query().ToMappedItemsAsync<Persistence.MovementKind, Contracts.MovementKindCollection, Contracts.MovementKind>(MovementKindMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.MovementStatusCollection> GetAllMovementStatusesAsync(CancellationToken cancellationToken = default)
        => ef.ThrowIfNull().Model<Persistence.MovementStatus>().Query().ToMappedItemsAsync<Persistence.MovementStatus, Contracts.MovementStatusCollection, Contracts.MovementStatus>(MovementStatusMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.SubCategoryCollection> GetAllSubCategoriesAsync(CancellationToken cancellationToken = default)
        => ef.ThrowIfNull().Model<Persistence.SubCategory>().Query().ToMappedItemsAsync<Persistence.SubCategory, Contracts.SubCategoryCollection, Contracts.SubCategory>(SubCategoryMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.UnitOfMeasureCollection> GetAllUnitsOfMeasureAsync(CancellationToken cancellationToken = default)
        => ef.ThrowIfNull().Model<Persistence.UnitOfMeasure>().Query().ToMappedItemsAsync<Persistence.UnitOfMeasure, Contracts.UnitOfMeasureCollection, Contracts.UnitOfMeasure>(UnitOfMeasureMapper.Map, cancellationToken);
}

#nullable restore