@port = 7129
@hostname = localhost
@scheme = https
@host = {{scheme}}://{{hostname}}:{{port}}


### Health endpoint
GET {{host}}/api/health

# Swagger

### Get openapi json
GET {{host}}/api/openapi/1.0

### Get swagger json
GET {{host}}/api/swagger.json

### Get swagger UI
GET {{host}}/api/swagger/ui

# Employee CRUD operations
# todo: add payloads
### Get all Employees
GET {{host}}/api/employees
x-correlation-id: 123-my-correlation-id-getall

### Get Employee
GET {{host}}/api/employees/3fa85f64-5717-4562-b3fc-2c963f66afa6
x-correlation-id: 123-my-correlation-id-get

### Create Employee
POST {{host}}/api/employees
x-correlation-id: 123-my-correlation-id-create
Content-Type: application/json

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "email": "alice@alice.com",
  "firstName": "Alice",
  "lastName": "Doe",
  "gender": "F",
  "birthday": "2000-09-28T15:36:55.730Z",
  "startDate": "2022-09-01T15:36:55.730Z",
  "phoneNo": "765-123-5687"
}

### Update Employee
# todo: this fails with The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded
PUT {{host}}/api/employees/3fa85f64-5717-4562-b3fc-2c963f66afa6
x-correlation-id: 123-my-correlation-id-update
Content-Type: application/json

{
  "email": "alice@alice.com",
  "firstName": "Alice",
  "lastName": "Doe",
  "gender": "F",
  "birthday": "2000-09-28T15:36:55.730Z",
  "startDate": "2022-09-01T15:36:55.730Z",
  "phoneNo": "765-123-0000"
}

### Patch Employee
PATCH {{host}}/api/employees/3fa85f64-5717-4562-b3fc-2c963f66afa6
x-correlation-id: 123-my-correlation-id
Content-Type: application/json
If-Match: AAAAAAAACBg=

{
  "phoneNo": "765-123-0000"
}

### Delete Employee
DELETE {{host}}/api/employees/3fa85f64-5717-4562-b3fc-2c963f66afa6
x-correlation-id: 123-my-correlation-id


### Employee Verification scenario with service bus
POST {{host}}/api/employee/verify
Content-Type: application/json
x-correlation-id: 123-my-correlation-id-verify

{
    "name": "John",
    "age": 27,
    "gender": "male"
}