# requires following env variables:
# * secret variable - PULUMI_CONFIG_PASSPHRASE - KeyVault can be used instead of pass phrase, see: https://www.pulumi.com/docs/intro/concepts/secrets/#azure-key-vault

name: Infra-Destroy_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
- name: stack_name
  type: string
  displayName: Name of the stack to delete
- name: env
  type: string
  displayName: Name of the environment in ADO - env, dev, etc.

variables:
- name: buildConfiguration
  value: 'Release'

trigger: none


stages:
- stage: Delete
  jobs:
    - template: templates/infra-destroy-template.yml
      parameters:
        AzureSubscription: $(AzureSubscription) # replace with the name of service connection
        env: ${{ parameters.env }}
        storageAccountName: pulumistatestore112
        stack_name: ${{ parameters.stack_name }}