/*
 * WARNING: This file is currently in an initial scaffolding state and will be (replaced) generated by 'app-name.CodeGen' in the future; any changes will be lost.
 */

namespace app-name.Application.Repositories;

/// <summary>Enables the underlying reference-data repository.</summary>
public partial interface IReferenceDataRepository;
