// <auto-generated/>

/*
 * This file is automatically generated by 'Contoso.Customers.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace Contoso.Customers.Application;

/// <summary>Provides the <see cref="IReferenceDataProvider"/> implementation.</summary>
[ScopedService<IReferenceDataProvider>]
public partial class ReferenceDataService(IReferenceDataRepository repository) : IReferenceDataProvider
{
    private readonly IReferenceDataRepository _repository = repository.ThrowIfNull();

    /// <inheritdoc/>
    public IEnumerable<(Type, Type)> Types =>
    [
        (typeof(CustomerType), typeof(CustomerTypeCollection)),
        (typeof(ContactMethod), typeof(ContactMethodCollection)),
    ];

    /// <inheritdoc/>
    public IEnumerable<(string, Type)> AlternateNames =>
    [
        ( "customer-types", typeof(CustomerType) ),
        ( "contact-methods", typeof(ContactMethod) )
    ];

    /// <inheritdoc/>
    public virtual async Task<IReferenceDataCollection> GetAsync(Type type, CancellationToken cancellationToken = default) => type switch
    {
        _ when type == typeof(CustomerType) => await _repository.GetAllCustomerTypesAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(ContactMethod) => await _repository.GetAllContactMethodsAsync(cancellationToken).ConfigureAwait(false),
        _ => throw new InvalidOperationException($"Type {type.FullName} is not a known {nameof(IReferenceData)}.")
    };
}

#nullable restore
