CREATE OR ALTER PROCEDURE [Orders].[spOutboxEnqueue]
  @TenantId AS NVARCHAR(255) = NULL,
  @PartitionId AS INT,
  @Destination AS NVARCHAR(255),
  @Event AS NVARCHAR(MAX),
  @EnqueuedUtc AS DATETIME2 = NULL,
  @AvailableUtc AS DATETIME2 = NULL
AS
BEGIN
  /*
   * This file is automatically generated by 'Contoso.Orders.Database'; any changes will be lost.
   */

  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  DECLARE @Now DATETIME2 = SYSUTCDATETIME();
  DECLARE @EffectiveTenantId NVARCHAR(255) = COALESCE(@TenantId, '(none)');

  INSERT INTO [Orders].[Outbox] (
    [TenantId],
    [PartitionId],
    [Destination],
    [Event],
    [EnqueuedUtc],
    [AvailableUtc]
  )
  VALUES (
    @EffectiveTenantId,
    @PartitionId,
    @Destination,
    @Event,
    COALESCE(@EnqueuedUtc, @Now),
    COALESCE(@AvailableUtc, COALESCE(@EnqueuedUtc, @Now))
  )
END