CREATE OR ALTER PROCEDURE [Orders].[spOutboxBatchComplete]
  @LeaseId UNIQUEIDENTIFIER,
  @DequeuedUtc DATETIME2 NULL
AS
BEGIN
  /*
   * This file is automatically generated by 'Contoso.Orders.Database'; any changes will be lost.
   *
   * Marks a batch as completed by LeaseId, releasing the lease and making way for the next batch.
   * > Returns:
   *   0 = Success.
   *  -1 = No rows updated (e.g. already completed or invalid LeaseId).
   */

  SET NOCOUNT ON;
  SET XACT_ABORT ON;
  SET LOCK_TIMEOUT 5000; -- Milliseconds.
  SET TRANSACTION ISOLATION LEVEL READ COMMITTED

  DECLARE @Now DATETIME2 = SYSUTCDATETIME();

  BEGIN TRY
    BEGIN TRAN;

    -- 1) Complete the batch.
    UPDATE o
      SET o.[Status] = 2,
          o.[LeaseId] = NULL,
          o.[LeaseUntilUtc] = NULL,
          o.[DequeuedUtc] = COALESCE(@DequeuedUtc, @Now)
    FROM [Orders].[Outbox] AS o WITH (UPDLOCK, ROWLOCK)
    WHERE o.[LeaseId] = @LeaseId
      AND o.[Status] = 1;

    IF (@@ROWCOUNT = 0)
    BEGIN
      COMMIT;
      RETURN -1; -- No rows updated.
    END

    COMMIT;

    -- 2) Release the partition lease where identified.
    BEGIN TRY
      EXEC [Orders].[spOutboxLeaseRelease] @LeaseId;
    END TRY
    BEGIN CATCH
      -- Ignore: lease will expire. Don't fail completion.
    END CATCH

    RETURN 0
  END TRY
  BEGIN CATCH
    IF (XACT_STATE() <> 0) ROLLBACK;
    THROW; -- Re-throw preserves error details to caller.
  END CATCH

END