CREATE OR ALTER PROCEDURE [Orders].[spOutboxLeaseAcquire]
  @TenantId NVARCHAR(255) = NULL,
  @PartitionId INT,
  @LeaseId UNIQUEIDENTIFIER,
  @LeaseSeconds INT,
  @LeaseUntilUtc DATETIME2 OUTPUT
AS
BEGIN
  /*
   * This file is automatically generated by 'Contoso.Orders.Database'; any changes will be lost.
   *
   * Attempts to acquire a lease for a tenant/partition, returning success status and lease until timestamp.
   * > Returns:
   *   0 = Lease acquired; caller may proceed with batch claim.
   *  -1 = Lease not acquired; caller should backoff and retry.
   *
   * Notes:
   * - The procedure will return -1 where lease acquisition is unsuccessful, including where another active lease exists.
   * - The caller should implement an appropriate retry/backoff strategy where -1 is returned, including randomization to avoid thundering herd issues.
   */

  SET NOCOUNT ON;
  SET XACT_ABORT ON;
  SET LOCK_TIMEOUT 5000; -- Milliseconds.
  SET TRANSACTION ISOLATION LEVEL READ COMMITTED

  DECLARE @Now DATETIME2 = SYSUTCDATETIME();
  DECLARE @Until DATETIME2 = DATEADD(SECOND, @LeaseSeconds, @Now)
  DECLARE @EffectiveTenantId NVARCHAR(255) = COALESCE(@TenantId, '(none)');

  BEGIN TRY
    BEGIN TRAN;

    -- 1) Ensure the row exists (self-seeding); lock the key-range for this PartitionId to avoid insert races.
    IF NOT EXISTS (
      SELECT 1
      FROM [Orders].[OutboxLease] WITH (UPDLOCK, HOLDLOCK)
      WHERE [TenantId] = @EffectiveTenantId AND [PartitionId] = @PartitionId
    )
    BEGIN
      INSERT INTO [Orders].[OutboxLease] ([TenantId], [PartitionId])
      VALUES (@EffectiveTenantId, @PartitionId);
    END

    -- 2) Attempt to acquire lease where expired/empty.
    UPDATE ol
      SET ol.[LeaseId] = @LeaseId,
          ol.[LeaseUntilUtc] = @Until
      FROM [Orders].[OutboxLease] AS ol WITH (UPDLOCK, ROWLOCK)
      WHERE ol.[PartitionId] = @PartitionId
        AND ol.[TenantId] = @EffectiveTenantId
        AND (ol.[LeaseUntilUtc] IS NULL OR ol.[LeaseUntilUtc] <= @Now)
        OPTION (RECOMPILE);

    -- 3) Commit and return lease success status.
    DECLARE @Rows INT = @@ROWCOUNT;

    COMMIT;

    IF @Rows = 1
    BEGIN
      SET @LeaseUntilUtc = @Until;
      RETURN 0; -- Lease successful.
    END

    SET @LeaseUntilUtc = NULL;
    RETURN -1; -- Lease unsuccessful.
  END TRY
  BEGIN CATCH
    IF (XACT_STATE() <> 0) ROLLBACK;
    THROW; -- Re-throw preserves error details to caller.
  END CATCH
END